### ISSUE TITLE
Reproducing scores in example

### ISSUE THREAD

**Issue by Alex-Fabbri** [recitalAI/summa-qa#2]
HI! 

I'm using your metric and wanted to just reproduce the numbers in the README, but I'm getting slightly different numbers:

summary 1: {'avg_prob': 0.10436534642455324, 'avg_fscore': 0.19754273504273503}
summary 2: {'avg_prob': 0.006622146878119868, 'avg_fscore': 0.0}
{'avg_prob': 0.05549374665133655, 'avg_fscore': 0.09877136752136752}

Do you have any thoughts on the cause of this variability? 

I'm attaching the result of running pip freeze > requiresments.txt. I'm using Python 3.6.8. 
[requirements.txt](https://github.com/recitalAI/summa-qa/files/4395300/requirements.txt)

Thank you!

**Comment by ThomasScialom** [comment]
Hi Alex, thanks for reporting this. Indeed we observe your same scores. This might be due to a change in the QA model provided by HuggingFace. However, these scores are comparable with the previously reported ones, so the whole process is generally not impacted by such change. We will update the scores in the README soon.

**Comment by Alex-Fabbri** [comment]
Hi Thomas, That makes sense. Thanks for following up!
